project:
  type: website

website:
  title: "AFFORD_docsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Proposal.md
      - Storage.md
      - Data.Rmd
      - About.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual

