---
title: "AFFORD Thumbs"
author: "G.Fraga Gonzalez"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: no
runhead: AFFORD-THUMB
#abstract: 'Here you can search for the  data you want'
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Database {.tabset}

## Repository finder

Last compiled: `r Sys.Date()`

```{r, echo=F, results="asis"}
library(dplyr)
library(knitr)
library(kableExtra)

# read data
fileinput <- 'C:/Users/GFraga/Desktop/AFFORD_THUMBS/Metadata.xlsx' # Path will change to read file from github repo

# here some validation checks should be included 
data <- readxl::read_excel(fileinput)

#plot table
library(reactable)
reactable::reactable(data, filterable = TRUE, minRows = 10, searchable = TRUE, columns = list( 
                        Link = colDef(cell = function(value, index) {
                          # Render text of 'Link' column as a hyperlink
                          htmltools::tags$a(href = url, target = "_blank", as.character(value))
                        }))) 

```



